.PHONY: ctest ptest

ctest:
	gcc backtracking_combination.c -o backtracking_combination.out
	./backtracking_combination.out

ptest:
	gcc backtracking_permutation.c -o backtracking_permutation.out
	./backtracking_permutation.out

clean:
	rm -f *.out
